version: "3.3"
services:
  db:
    image: postgres:12.3
    container_name: ecoleta-postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    logging:
      options:
        max-size: "5m"
        max-file: "5"
